#!/usr/bin/env bash
set -Eeuo pipefail

mkdir -p image.root.dir
mount -o loop "$1" image.root.dir
trap "umount image.root.dir && rmdir image.root.dir" EXIT
rm -f "$2"
mksquashfs image.root.dir "$2" -comp zstd
